services:
  db:
    image: postgres:15
    environment:
        POSTGRES_DB: translations
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
       - app-translator-volume:/var/lib/postgresql/data  # Volume
       - /db/init.sql:/docker-entrypoint-initdb.d/init.sql # Bind Mount
    networks:
      - db_network


  backend:
    build: ./backend
    environment: 
      DATABASE_URL: postgres://postgres:postgres@db:5432/translations
    networks: [db_network, translator_network, frontend_network]

    depends_on:
     - db
     - translator

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - frontend_network
  
  translator:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    networks:
      - translator_network


networks:
  frontend_network:
    driver: bridge
  db_network:
    driver: bridge
  translator_network:
    driver: bridge

volumes:
  app-translator-volume:
